[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express", "serverless-http", "@prisma/client", "@prisma/adapter-pg", "pg", "cors"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/backend/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
